from datetime import datetime, timedelta, timezone
from dataclasses import replace
import time
import pytest

from app.execution.circuit_breaker import CircuitBreaker, CircuitState
from app.execution.authorization import ExecutionAuthorization
from app.decision.versioning import versions
from app.config import POLICY_VERSION, MODEL_VERSION


def test_circuit_breaker_opens_after_n_failures():
    cb = CircuitBreaker(failure_threshold=3, recovery_timeout=60.0)
    assert cb.allow_request() is True
    assert cb.state == CircuitState.CLOSED

    cb.record_failure()
    assert cb.allow_request() is True
    cb.record_failure()
    assert cb.allow_request() is True

    # 3rd failure reaches failure_threshold -> OPEN
    cb.record_failure()
    assert cb.state == CircuitState.OPEN
    assert cb.allow_request() is False


def test_circuit_breaker_half_open_single_probe(monkeypatch):
    current_time = 1000.0
    monkeypatch.setattr(time, "monotonic", lambda: current_time)

    cb = CircuitBreaker(failure_threshold=3, recovery_timeout=60.0)
    for _ in range(3):
        cb.record_failure()
    assert cb.state == CircuitState.OPEN
    assert cb.allow_request() is False

    # Elapse recovery_timeout (60s -> advance 61s)
    current_time += 61.0

    # First request transitions to HALF_OPEN and is allowed as probe
    assert cb.allow_request() is True
    assert cb.state == CircuitState.HALF_OPEN

    # Subsequent requests in HALF_OPEN before probe result must be blocked
    assert cb.allow_request() is False


def test_circuit_breaker_half_open_success_closes(monkeypatch):
    current_time = 1000.0
    monkeypatch.setattr(time, "monotonic", lambda: current_time)

    cb = CircuitBreaker(failure_threshold=3, recovery_timeout=60.0)
    for _ in range(3):
        cb.record_failure()

    # Elapse timeout and send probe
    current_time += 61.0
    assert cb.allow_request() is True
    assert cb.state == CircuitState.HALF_OPEN

    # Successful probe resets breaker to CLOSED
    cb.record_success()
    assert cb.state == CircuitState.CLOSED
    assert cb.failure_count == 0
    assert cb.allow_request() is True


def test_stale_authorization_rejected():
    auth = ExecutionAuthorization.create(
        case_id="CASE-123",
        action="MANUAL_RECOVERY",
        policy_version=POLICY_VERSION,
        model_version=MODEL_VERSION,
    )
    # Valid immediately after creation
    assert auth.is_valid(POLICY_VERSION, MODEL_VERSION) is True

    # Expire authorization by setting expires_at to 1 second in the past
    stale_auth = replace(auth, expires_at=datetime.now(timezone.utc) - timedelta(seconds=1))
    assert stale_auth.is_valid(POLICY_VERSION, MODEL_VERSION) is False


def test_model_policy_version_mismatch_blocked():
    """Verify that an authorization with a mismatched model or policy version blocks execution."""
    from app.pipeline import RecoveryPipeline

    pipeline = RecoveryPipeline()
    # Create an authorization generated by an outdated/incompatible policy/model
    stale_auth = ExecutionAuthorization.create(
        case_id="CASE-MISMATCH",
        action="MANUAL_RECOVERY",
        policy_version="policy-v1-deprecated",
        model_version="model-v1-deprecated",
    )
    assert stale_auth.is_valid(POLICY_VERSION, MODEL_VERSION) is False

    # The pipeline should reject or block execution when given a mismatched authorization,
    # but currently lacks a version-gate check on execution intents.
    case = {
        "event_id": "CASE-MISMATCH",
        "amount": 1999,
        "subscription_status": "pending",
        "invoice_status": "issued",
        "payment_method_type": "international_card",
        "native_retry_scheduled": False,
        "authorization": stale_auth,
        "is_live": True,
    }
    decision = pipeline.process(case)
    # This should block or escalate due to version mismatch, but currently executes/approves:
    assert decision["chosen_action"] == "ESCALATE"
    assert decision["execution_status"] in ("BLOCKED", "NO_RECOVERY")


def test_malformed_llm_output_fails_closed_and_preserves_audit(monkeypatch):
    """Scenario 1: Malformed LLM response fails closed to ESCALATE, preserves raw output in audit, and batch loop continues."""
    import json
    from unittest.mock import MagicMock, patch
    import app.db as db
    from app.pipeline import RecoveryPipeline
    from app.execution.simulator import SubscriptionSimulator

    db.init_db()

    pipeline = RecoveryPipeline(simulator=SubscriptionSimulator(42))
    raw_bad_json = '{"decline_class": "invented_sixth_category_unauthorized", "confidence": "invalid_float", "unexpected": true}'
    mock_resp = MagicMock()
    mock_resp.json.return_value = {"choices": [{"message": {"content": raw_bad_json}}]}
    mock_resp.raise_for_status = MagicMock()

    batch = [
        {
            "event_id": "EVT-TEST-01-CLEAN",
            "customer_name": "Customer 1",
            "amount": 1999.0,
            "subscription_status": "pending",
            "invoice_status": "issued",
            "payment_method_type": "international_card",
            "failure_reason": "insufficient_funds",
            "attempt_number": 2,
            "contact_count_7d": 1,
            "customer_opted_out": False,
            "native_retry_scheduled": False,
            "current_time": "2026-08-29T12:00:00+05:30",
        },
        {
            "event_id": "EVT-TEST-02-MALFORMED",
            "customer_name": "Customer 2",
            "amount": 2499.0,
            "subscription_status": "pending",
            "invoice_status": "issued",
            "payment_method_type": "international_card",
            "failure_reason": "CUSTOM_HDFC_UNRECOGNIZED_CODE_404",
            "attempt_number": 2,
            "contact_count_7d": 1,
            "customer_opted_out": False,
            "native_retry_scheduled": False,
            "current_time": "2026-08-29T12:00:00+05:30",
        },
        {
            "event_id": "EVT-TEST-03-CLEAN",
            "customer_name": "Customer 3",
            "amount": 1499.0,
            "subscription_status": "pending",
            "invoice_status": "issued",
            "payment_method_type": "international_card",
            "failure_reason": "card_expired",
            "attempt_number": 2,
            "contact_count_7d": 1,
            "customer_opted_out": False,
            "native_retry_scheduled": False,
            "current_time": "2026-08-29T12:00:00+05:30",
        },
    ]

    results = []
    with patch("requests.post", return_value=mock_resp):
        with patch("app.diagnosis.GROQ_API_KEY", "mock-groq-key"):
            for case in batch:
                dec = pipeline.process(case, is_preview=False)
                results.append(dec)

    # 1. Assert batch processed without crashing
    assert len(results) == 3

    # 2. Assert Case 2 failed closed
    d2 = results[1]
    diag2 = d2["diagnosis"]
    assert diag2["source"] == "llm_failed"
    assert diag2["decline_class"] == "unclear"
    assert diag2["raw_llm_output"] == raw_bad_json
    assert "LLM schema validation failure" in diag2["reasoning"] or "LLM Output Pydantic validation failed" in str(diag2)

    # 3. Assert audit log row contains diagnosis and raw bad output
    with db.get_conn() as conn:
        row = conn.execute("SELECT payload_json FROM audit_logs WHERE event_id = ?", ("EVT-TEST-02-MALFORMED",)).fetchone()
        assert row is not None
        payload = row["payload_json"] if isinstance(row["payload_json"], dict) else json.loads(row["payload_json"])
        assert payload["diagnosis"]["source"] == "llm_failed"
        assert payload["diagnosis"]["raw_llm_output"] == raw_bad_json


def test_malformed_llm_messaging_fails_closed_and_logs_audit(monkeypatch):
    """Scenario 2: Malformed LLM message-generation output fails closed, demotes to ESCALATE, and records audit entry."""
    import json
    import app.db as db
    from app.pipeline import RecoveryPipeline
    from app.execution.simulator import SubscriptionSimulator
    from unittest.mock import MagicMock, patch

    db.init_db()

    pipeline = RecoveryPipeline(simulator=SubscriptionSimulator(42))

    case = {
        "event_id": "EVT-TEST-MSG-MALFORMED",
        "customer_name": "Kavita Rao",
        "amount": 2499.0,
        "subscription_status": "pending",
        "invoice_status": "issued",
        "payment_method_type": "international_card",
        "failure_reason": "insufficient_funds",
        "attempt_number": 2,
        "contact_count_7d": 1,
        "customer_opted_out": False,
        "native_retry_scheduled": False,
        "current_time": "2026-08-29T12:00:00+05:30",
    }

    # Mock Groq to return malformed output missing required fields
    raw_bad_msg_json = '{"message": "Please pay ₹2,499.00 here: https://rzp.io/rzp/demo"}'
    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.json.return_value = {"choices": [{"message": {"content": raw_bad_msg_json}}]}

    with patch("requests.post", return_value=mock_resp):
        with patch("app.messaging.GROQ_API_KEY", "mock-groq-key"):
            decision = pipeline.process(case, is_preview=False)

    # Assertions
    assert decision["chosen_action"] == "ESCALATE"
    gen_msg = decision.get("generated_message")
    assert gen_msg is not None
    assert gen_msg["source"] == "llm_failed"
    assert gen_msg["tone_check_passed"] is False
    assert gen_msg["status"] == "BLOCKED_TONE_CHECK"

    # Verify audit persistence
    with db.get_conn() as conn:
        row = conn.execute("SELECT payload_json FROM audit_logs WHERE event_id = ?", ("EVT-TEST-MSG-MALFORMED",)).fetchone()
        assert row is not None
        payload = row["payload_json"] if isinstance(row["payload_json"], dict) else json.loads(row["payload_json"])
        assert payload["generated_message"]["source"] == "llm_failed"
        assert payload["generated_message"]["status"] == "BLOCKED_TONE_CHECK"


def test_audit_tamper_attempt_raises_engine_rejection():
    """Scenario 3: Audit tamper attempt (UPDATE/DELETE) raises engine-level error (IntegrityError/InsufficientPrivilege)."""
    import app.db as db
    from app.audit.logger import AuditLogger

    db.init_db()

    from app.decision.replay import DecisionStore
    DecisionStore().save({
        "decision_id": "dec_tamper_test_01",
        "case_id": "EVT-TAMPER-DRILL-01",
        "features": {},
        "chosen_action": "ESCALATE",
    })
    logger = AuditLogger()
    record = {
        "decision_id": "dec_tamper_test_01",
        "event_id": "EVT-TAMPER-DRILL-01",
        "case_id": "EVT-TAMPER-DRILL-01",
        "timestamp": "2026-08-29T12:00:00Z",
        "payload": {"status": "AUTHENTIC_RECORD"},
    }
    logger.log(record)

    # 1. Attempt UPDATE -> must raise IntegrityError from prevent_audit_update trigger
    with pytest.raises(Exception) as exc_update:
        with db.get_conn() as conn:
            conn.execute(
                "UPDATE audit_logs SET payload_json = ? WHERE event_id = ?",
                ('{"tampered": true}', "EVT-TAMPER-DRILL-01"),
            )
    assert "audit_log is append-only: UPDATE forbidden" in str(exc_update.value) or "permission denied" in str(exc_update.value)

    # 2. Attempt DELETE -> must raise IntegrityError from prevent_audit_delete trigger
    with pytest.raises(Exception) as exc_delete:
        with db.get_conn() as conn:
            conn.execute("DELETE FROM audit_logs WHERE event_id = ?", ("EVT-TAMPER-DRILL-01",))
    assert "audit_log is append-only: DELETE forbidden" in str(exc_delete.value) or "permission denied" in str(exc_delete.value)


def test_provider_down_circuit_breaker_short_circuits_and_logs_audit(monkeypatch):
    """Scenario 4: Gateway provider down trips circuit breaker, short-circuits further calls, routes safely to ESCALATE."""
    import json
    import app.db as db
    from app.pipeline import RecoveryPipeline
    from app.execution.simulator import SubscriptionSimulator
    from app.execution.live_executor import LiveExecutor
    from app.execution.razorpay import RazorpayAPIError
    from app.execution.circuit_breaker import CircuitBreaker, CircuitState

    db.init_db()

    class MockFailingAdapter:
        def __init__(self):
            self.call_count = 0
        def create_payment_link(self, *args, **kwargs):
            self.call_count += 1
            raise RazorpayAPIError("503 Service Unavailable: Gateway Switch Down")
        def fetch_payment_link(self, *args, **kwargs):
            self.call_count += 1
            raise RazorpayAPIError("503 Service Unavailable: Gateway Switch Down")

    mock_adapter = MockFailingAdapter()
    cb = CircuitBreaker(failure_threshold=3, recovery_timeout=60.0)
    pipeline = RecoveryPipeline(simulator=SubscriptionSimulator(42))
    pipeline.live_executor = LiveExecutor(adapter=mock_adapter)
    pipeline.circuit_breaker = cb

    cases = [
        {
            "event_id": f"EVT-CB-TEST-{i:02d}",
            "customer_name": f"Customer {i}",
            "amount": 2499.0,
            "subscription_status": "pending",
            "invoice_status": "issued",
            "payment_method_type": "international_card",
            "attempt_number": 2,
            "contact_count_7d": 1,
            "customer_opted_out": False,
            "native_retry_scheduled": False,
            "current_time": "2026-08-29T12:00:00+05:30",
            "is_live": True,
        }
        for i in range(1, 6)
    ]

    results = [pipeline.process(c, is_preview=False) for c in cases]

    # (a) Circuit Breaker transitioned to OPEN
    assert cb.state == CircuitState.OPEN

    # (b) External call count capped at 3 (requests 4 and 5 short-circuited)
    assert mock_adapter.call_count == 3

    # (c) Requests 4 & 5 routed safely without silent drops
    assert results[3]["chosen_action"] in ("ESCALATE", "WAIT")
    assert results[3]["execution_status"] == "BLOCKED_CIRCUIT_OPEN"
    assert results[4]["chosen_action"] in ("ESCALATE", "WAIT")
    assert results[4]["execution_status"] == "BLOCKED_CIRCUIT_OPEN"

    # (d) Audit rows exist for all 5 attempts
    with db.get_conn() as conn:
        for c in cases:
            count = conn.execute("SELECT COUNT(*) FROM audit_logs WHERE event_id = ?", (c["event_id"],)).fetchone()[0]
            assert count >= 1


def test_crash_between_authorization_and_razorpay_call_preserves_resumable_outbox_intent(monkeypatch):
    """
    Simulate a crash occurring immediately after authorization & transactional outbox persistence,
    BEFORE the outbound Razorpay network call.
    Verify that upon process restart/recovery, the pending intent is preserved in a valid, resumable state.
    """
    import app.db as db
    from app.pipeline import RecoveryPipeline
    from app.execution.simulator import SubscriptionSimulator
    from app.execution.outbox import get_pending_intents, claim_pending_intent, mark_intent_status

    db.init_db()

    case_id = f"EVT-CRASH-TEST-{int(time.time())}"
    case = {
        "event_id": case_id,
        "customer_name": "Crash Test Customer",
        "amount": 2499.0,
        "subscription_status": "pending",
        "invoice_status": "issued",
        "payment_method_type": "international_card",
        "attempt_number": 1,
        "contact_count_7d": 0,
        "customer_opted_out": False,
        "native_retry_scheduled": False,
        "current_time": "2026-08-29T12:00:00+05:30",
        "is_live": True,
    }

    # 1. Pipeline instance 1 crashes right as _execute_live is called
    pipe_pre_crash = RecoveryPipeline(simulator=SubscriptionSimulator(42))

    class SimulatedProcessCrash(Exception):
        pass

    def crash_before_external_call(*args, **kwargs):
        raise SimulatedProcessCrash("Simulated worker crash / SIGKILL immediately before outbound Razorpay call")

    monkeypatch.setattr("app.pipeline.claim_pending_intent", crash_before_external_call)

    with pytest.raises(SimulatedProcessCrash):
        pipe_pre_crash.process(case, is_preview=False)

    # 2. Worker restarts (new pipeline / worker process)
    # The outbox intent must be present in 'PENDING' state with durable authorization
    target_intents = get_pending_intents(case_id=case_id)
    assert len(target_intents) == 1
    intent = target_intents[0]
    assert intent["status"] == "PENDING"
    assert intent["action"] in ("MANUAL_RECOVERY", "NUDGE")

    # Assert decision record is durably present in decision_records
    with db.get_conn() as conn:
        dec_row = conn.execute("SELECT * FROM decision_records WHERE decision_id = ?", (intent["decision_id"],)).fetchone()
        assert dec_row is not None
        assert dec_row["case_id"] == case_id

    # 3. Resumed worker claims intent and finishes dispatch exactly once
    claimed = claim_pending_intent(intent["id"])
    assert claimed is not None
    assert claimed["status"] == "PROCESSING"

    # Worker calls Razorpay provider and stores response
    mark_intent_status(
        intent["id"],
        "EXECUTION_REQUESTED",
        {
            "status": "EXECUTION_REQUESTED",
            "payment_link_id": "plink_resumed_123",
            "payment_link_url": "https://rzp.io/rzp/resumed",
        },
    )

    with db.get_conn() as conn:
        final_intent = conn.execute("SELECT * FROM execution_intents WHERE id = ?", (intent["id"],)).fetchone()
        assert final_intent["status"] == "EXECUTION_REQUESTED"
        assert "plink_resumed_123" in str(final_intent["result_json"])
