from datetime import datetime, timedelta, timezone
from dataclasses import replace
import time
import pytest

from app.execution.circuit_breaker import CircuitBreaker, CircuitState
from app.execution.authorization import ExecutionAuthorization
from app.decision.versioning import versions
from app.config import POLICY_VERSION, MODEL_VERSION


def test_circuit_breaker_opens_after_n_failures():
    cb = CircuitBreaker(failure_threshold=3, recovery_timeout=60.0)
    assert cb.allow_request() is True
    assert cb.state == CircuitState.CLOSED

    cb.record_failure()
    assert cb.allow_request() is True
    cb.record_failure()
    assert cb.allow_request() is True

    # 3rd failure reaches failure_threshold -> OPEN
    cb.record_failure()
    assert cb.state == CircuitState.OPEN
    assert cb.allow_request() is False


def test_circuit_breaker_half_open_single_probe(monkeypatch):
    current_time = 1000.0
    monkeypatch.setattr(time, "monotonic", lambda: current_time)

    cb = CircuitBreaker(failure_threshold=3, recovery_timeout=60.0)
    for _ in range(3):
        cb.record_failure()
    assert cb.state == CircuitState.OPEN
    assert cb.allow_request() is False

    # Elapse recovery_timeout (60s -> advance 61s)
    current_time += 61.0

    # First request transitions to HALF_OPEN and is allowed as probe
    assert cb.allow_request() is True
    assert cb.state == CircuitState.HALF_OPEN

    # Subsequent requests in HALF_OPEN before probe result must be blocked
    assert cb.allow_request() is False


def test_circuit_breaker_half_open_success_closes(monkeypatch):
    current_time = 1000.0
    monkeypatch.setattr(time, "monotonic", lambda: current_time)

    cb = CircuitBreaker(failure_threshold=3, recovery_timeout=60.0)
    for _ in range(3):
        cb.record_failure()

    # Elapse timeout and send probe
    current_time += 61.0
    assert cb.allow_request() is True
    assert cb.state == CircuitState.HALF_OPEN

    # Successful probe resets breaker to CLOSED
    cb.record_success()
    assert cb.state == CircuitState.CLOSED
    assert cb.failure_count == 0
    assert cb.allow_request() is True


def test_stale_authorization_rejected():
    auth = ExecutionAuthorization.create(
        case_id="CASE-123",
        action="MANUAL_RECOVERY",
        policy_version=POLICY_VERSION,
        model_version=MODEL_VERSION,
    )
    # Valid immediately after creation
    assert auth.is_valid(POLICY_VERSION, MODEL_VERSION) is True

    # Expire authorization by setting expires_at to 1 second in the past
    stale_auth = replace(auth, expires_at=datetime.now(timezone.utc) - timedelta(seconds=1))
    assert stale_auth.is_valid(POLICY_VERSION, MODEL_VERSION) is False


def test_model_policy_version_mismatch_blocked():
    """Verify that an authorization with a mismatched model or policy version blocks execution."""
    from app.pipeline import RecoveryPipeline

    pipeline = RecoveryPipeline()
    # Create an authorization generated by an outdated/incompatible policy/model
    stale_auth = ExecutionAuthorization.create(
        case_id="CASE-MISMATCH",
        action="MANUAL_RECOVERY",
        policy_version="policy-v1-deprecated",
        model_version="model-v1-deprecated",
    )
    assert stale_auth.is_valid(POLICY_VERSION, MODEL_VERSION) is False

    # The pipeline should reject or block execution when given a mismatched authorization,
    # but currently lacks a version-gate check on execution intents.
    case = {
        "event_id": "CASE-MISMATCH",
        "amount": 1999,
        "subscription_status": "pending",
        "invoice_status": "issued",
        "payment_method_type": "international_card",
        "native_retry_scheduled": False,
        "authorization": stale_auth,
        "is_live": True,
    }
    decision = pipeline.process(case)
    # This should block or escalate due to version mismatch, but currently executes/approves:
    assert decision["chosen_action"] == "ESCALATE"
    assert decision["execution_status"] in ("BLOCKED", "NO_RECOVERY")
