from datetime import datetime, timedelta, timezone
from dataclasses import replace
import time
import pytest

from app.execution.circuit_breaker import CircuitBreaker, CircuitState
from app.execution.authorization import ExecutionAuthorization
from app.decision.versioning import versions
from app.config import POLICY_VERSION, MODEL_VERSION


def test_circuit_breaker_opens_after_n_failures():
    cb = CircuitBreaker(failure_threshold=3, recovery_timeout=60.0)
    assert cb.allow_request() is True
    assert cb.state == CircuitState.CLOSED

    cb.record_failure()
    assert cb.allow_request() is True
    cb.record_failure()
    assert cb.allow_request() is True

    # 3rd failure reaches failure_threshold -> OPEN
    cb.record_failure()
    assert cb.state == CircuitState.OPEN
    assert cb.allow_request() is False


def test_circuit_breaker_half_open_single_probe(monkeypatch):
    current_time = 1000.0
    monkeypatch.setattr(time, "monotonic", lambda: current_time)

    cb = CircuitBreaker(failure_threshold=3, recovery_timeout=60.0)
    for _ in range(3):
        cb.record_failure()
    assert cb.state == CircuitState.OPEN
    assert cb.allow_request() is False

    # Elapse recovery_timeout (60s -> advance 61s)
    current_time += 61.0

    # First request transitions to HALF_OPEN and is allowed as probe
    assert cb.allow_request() is True
    assert cb.state == CircuitState.HALF_OPEN

    # Subsequent requests in HALF_OPEN before probe result must be blocked
    assert cb.allow_request() is False


def test_circuit_breaker_half_open_success_closes(monkeypatch):
    current_time = 1000.0
    monkeypatch.setattr(time, "monotonic", lambda: current_time)

    cb = CircuitBreaker(failure_threshold=3, recovery_timeout=60.0)
    for _ in range(3):
        cb.record_failure()

    # Elapse timeout and send probe
    current_time += 61.0
    assert cb.allow_request() is True
    assert cb.state == CircuitState.HALF_OPEN

    # Successful probe resets breaker to CLOSED
    cb.record_success()
    assert cb.state == CircuitState.CLOSED
    assert cb.failure_count == 0
    assert cb.allow_request() is True


def test_stale_authorization_rejected():
    auth = ExecutionAuthorization.create(
        case_id="CASE-123",
        action="MANUAL_RECOVERY",
        policy_version=POLICY_VERSION,
        model_version=MODEL_VERSION,
    )
    # Valid immediately after creation
    assert auth.is_valid(POLICY_VERSION, MODEL_VERSION) is True

    # Expire authorization by setting expires_at to 1 second in the past
    stale_auth = replace(auth, expires_at=datetime.now(timezone.utc) - timedelta(seconds=1))
    assert stale_auth.is_valid(POLICY_VERSION, MODEL_VERSION) is False


def test_model_policy_version_mismatch_blocked():
    """Verify that an authorization with a mismatched model or policy version blocks execution."""
    from app.pipeline import RecoveryPipeline

    pipeline = RecoveryPipeline()
    # Create an authorization generated by an outdated/incompatible policy/model
    stale_auth = ExecutionAuthorization.create(
        case_id="CASE-MISMATCH",
        action="MANUAL_RECOVERY",
        policy_version="policy-v1-deprecated",
        model_version="model-v1-deprecated",
    )
    assert stale_auth.is_valid(POLICY_VERSION, MODEL_VERSION) is False

    # The pipeline should reject or block execution when given a mismatched authorization,
    # but currently lacks a version-gate check on execution intents.
    case = {
        "event_id": "CASE-MISMATCH",
        "amount": 1999,
        "subscription_status": "pending",
        "invoice_status": "issued",
        "payment_method_type": "international_card",
        "native_retry_scheduled": False,
        "authorization": stale_auth,
        "is_live": True,
    }
    decision = pipeline.process(case)
    # This should block or escalate due to version mismatch, but currently executes/approves:
    assert decision["chosen_action"] == "ESCALATE"
    assert decision["execution_status"] in ("BLOCKED", "NO_RECOVERY")


def test_malformed_llm_output_fails_closed_and_preserves_audit(tmp_path, monkeypatch):
    """Scenario 1: Malformed LLM response fails closed to ESCALATE, preserves raw output in audit, and batch loop continues."""
    import json
    from unittest.mock import MagicMock, patch
    from app import config
    import app.db as db
    from app.pipeline import RecoveryPipeline
    from app.execution.simulator import SubscriptionSimulator

    monkeypatch.setattr(config, "DATABASE_PATH", tmp_path / "test_malformed.db")
    monkeypatch.setattr(db, "DATABASE_PATH", tmp_path / "test_malformed.db")
    db.init_db()

    pipeline = RecoveryPipeline(simulator=SubscriptionSimulator(42))
    raw_bad_json = '{"decline_class": "invented_sixth_category_unauthorized", "confidence": "invalid_float", "unexpected": true}'
    mock_resp = MagicMock()
    mock_resp.json.return_value = {"choices": [{"message": {"content": raw_bad_json}}]}
    mock_resp.raise_for_status = MagicMock()

    batch = [
        {
            "event_id": "EVT-TEST-01-CLEAN",
            "customer_name": "Customer 1",
            "amount": 1999.0,
            "subscription_status": "pending",
            "invoice_status": "issued",
            "payment_method_type": "international_card",
            "failure_reason": "insufficient_funds",
            "attempt_number": 2,
            "contact_count_7d": 1,
            "customer_opted_out": False,
            "native_retry_scheduled": False,
            "current_time": "2026-08-29T12:00:00+05:30",
        },
        {
            "event_id": "EVT-TEST-02-MALFORMED",
            "customer_name": "Customer 2",
            "amount": 2499.0,
            "subscription_status": "pending",
            "invoice_status": "issued",
            "payment_method_type": "international_card",
            "failure_reason": "CUSTOM_HDFC_UNRECOGNIZED_CODE_404",
            "attempt_number": 2,
            "contact_count_7d": 1,
            "customer_opted_out": False,
            "native_retry_scheduled": False,
            "current_time": "2026-08-29T12:00:00+05:30",
        },
        {
            "event_id": "EVT-TEST-03-CLEAN",
            "customer_name": "Customer 3",
            "amount": 1499.0,
            "subscription_status": "pending",
            "invoice_status": "issued",
            "payment_method_type": "international_card",
            "failure_reason": "card_expired",
            "attempt_number": 2,
            "contact_count_7d": 1,
            "customer_opted_out": False,
            "native_retry_scheduled": False,
            "current_time": "2026-08-29T12:00:00+05:30",
        },
    ]

    results = []
    with patch("requests.post", return_value=mock_resp):
        with patch("app.diagnosis.GROQ_API_KEY", "mock-groq-key"):
            for case in batch:
                dec = pipeline.process(case, is_preview=False)
                results.append(dec)

    # 1. Assert batch processed without crashing
    assert len(results) == 3

    # 2. Assert Case 2 failed closed
    d2 = results[1]
    diag2 = d2["diagnosis"]
    assert diag2["source"] == "llm_failed"
    assert diag2["decline_class"] == "unclear"
    assert diag2["raw_llm_output"] == raw_bad_json
    assert "LLM schema validation failure" in diag2["reasoning"] or "LLM Output Pydantic validation failed" in str(diag2)

    # 3. Assert audit log row contains diagnosis and raw bad output
    with db.get_conn() as conn:
        row = conn.execute("SELECT payload_json FROM audit_logs WHERE event_id = ?", ("EVT-TEST-02-MALFORMED",)).fetchone()
        assert row is not None
        payload = json.loads(row[0])
        assert payload["diagnosis"]["source"] == "llm_failed"
        assert payload["diagnosis"]["raw_llm_output"] == raw_bad_json


def test_provider_down_circuit_breaker_short_circuits_and_logs_audit(tmp_path, monkeypatch):
    """Scenario 2: Gateway provider down trips circuit breaker, short-circuits further calls, routes safely to ESCALATE."""
    import json
    from app import config
    import app.db as db
    from app.pipeline import RecoveryPipeline
    from app.execution.simulator import SubscriptionSimulator
    from app.execution.live_executor import LiveExecutor
    from app.execution.razorpay import RazorpayAPIError
    from app.execution.circuit_breaker import CircuitBreaker, CircuitState

    monkeypatch.setattr(config, "DATABASE_PATH", tmp_path / "test_cb_drill.db")
    monkeypatch.setattr(db, "DATABASE_PATH", tmp_path / "test_cb_drill.db")
    db.init_db()

    class MockFailingAdapter:
        def __init__(self):
            self.call_count = 0
        def create_payment_link(self, *args, **kwargs):
            self.call_count += 1
            raise RazorpayAPIError("503 Service Unavailable: Gateway Switch Down")
        def fetch_payment_link(self, *args, **kwargs):
            self.call_count += 1
            raise RazorpayAPIError("503 Service Unavailable: Gateway Switch Down")

    mock_adapter = MockFailingAdapter()
    cb = CircuitBreaker(failure_threshold=3, recovery_timeout=60.0)
    pipeline = RecoveryPipeline(simulator=SubscriptionSimulator(42))
    pipeline.live_executor = LiveExecutor(adapter=mock_adapter)
    pipeline.circuit_breaker = cb

    cases = [
        {
            "event_id": f"EVT-CB-TEST-{i:02d}",
            "customer_name": f"Customer {i}",
            "amount": 2499.0,
            "subscription_status": "pending",
            "invoice_status": "issued",
            "payment_method_type": "international_card",
            "attempt_number": 2,
            "contact_count_7d": 1,
            "customer_opted_out": False,
            "native_retry_scheduled": False,
            "current_time": "2026-08-29T12:00:00+05:30",
            "is_live": True,
        }
        for i in range(1, 6)
    ]

    results = [pipeline.process(c, is_preview=False) for c in cases]

    # (a) Circuit Breaker transitioned to OPEN
    assert cb.state == CircuitState.OPEN

    # (b) External call count capped at 3 (requests 4 and 5 short-circuited)
    assert mock_adapter.call_count == 3

    # (c) Requests 4 & 5 routed safely without silent drops
    assert results[3]["chosen_action"] in ("ESCALATE", "WAIT")
    assert results[3]["execution_status"] == "BLOCKED_CIRCUIT_OPEN"
    assert results[4]["chosen_action"] in ("ESCALATE", "WAIT")
    assert results[4]["execution_status"] == "BLOCKED_CIRCUIT_OPEN"

    # (d) Audit rows exist for all 5 attempts
    with db.get_conn() as conn:
        for c in cases:
            count = conn.execute("SELECT COUNT(*) FROM audit_logs WHERE event_id = ?", (c["event_id"],)).fetchone()[0]
            assert count >= 1
